
-- Missing user_notifications table
CREATE TABLE IF NOT EXISTS app20250904195901yvsuhcayno_v1.user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('post_published', 'post_failed', 'approval_needed', 'best_time', 'connection_error', 'quota_warning', 'welcome', 'setup_reminder')),
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_id ON app20250904195901yvsuhcayno_v1.user_notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_read ON app20250904195901yvsuhcayno_v1.user_notifications (user_id, read);
CREATE INDEX IF NOT EXISTS idx_user_notifications_created_at ON app20250904195901yvsuhcayno_v1.user_notifications (created_at);

-- Grant permissions
GRANT ALL ON app20250904195901yvsuhcayno_v1.user_notifications TO app20250904195901yvsuhcayno_v1_admin_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON app20250904195901yvsuhcayno_v1.user_notifications TO app20250904195901yvsuhcayno_v1_user;
