[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/next_api/system/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }
