[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { 
  NODE_ENV = "production",
  SERVICE_NAME = "omnipost-web",
  PORT = "3000"
}

[environments.staging]
variables = { 
  NODE_ENV = "staging",
  SERVICE_NAME = "omnipost-web",
  PORT = "3000"
}
