[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.ai"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { 
  NODE_ENV = "production",
  SERVICE_NAME = "omnipost-ai"
}

[environments.staging]
variables = { 
  NODE_ENV = "staging",
  SERVICE_NAME = "omnipost-ai"
}
