[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.worker"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
numReplicas = 1

[environments.production]
variables = { 
  NODE_ENV = "production",
  SERVICE_NAME = "omnipost-worker"
}

[environments.staging]
variables = { 
  NODE_ENV = "staging",
  SERVICE_NAME = "omnipost-worker"
}
