#!/bin/bash

# ===========================================
# RAILWAY ENVIRONMENT SETUP SCRIPT
# ===========================================

set -e

echo "🚂 Setting up Railway environment variables for OmniPost multi-service architecture..."

# Check if we're logged in to Railway
if ! railway whoami > /dev/null 2>&1; then
    echo "❌ Please login to Railway first: railway login"
    exit 1
fi

# Check if we're in the right project
PROJECT_NAME=$(railway status 2>/dev/null | grep "Project:" | awk '{print $2}')
if [ "$PROJECT_NAME" != "omnipost" ]; then
    echo "❌ Please link to the omnipost project first: railway link"
    exit 1
fi

echo "✅ Setting up environment for project: $PROJECT_NAME"

# ===========================================
# SHARED VARIABLES (Set on all services)
# ===========================================

echo "📝 Setting shared environment variables..."

# Core Application Settings
railway variables set NODE_ENV=production
railway variables set NEXT_PUBLIC_APP_NAME="OmniPost"

# Security & Authentication
echo "🔐 Setting security variables..."
railway variables set JWT_SECRET="$(openssl rand -base64 32)"
railway variables set HASH_SALT_KEY="$(openssl rand -base64 32)"

# Database Configuration (Supabase)
echo "🗄️  Setting database configuration..."
railway variables set POSTGREST_SCHEMA="public"

# Platform Integrations
echo "🌐 Setting platform integrations..."
# These need to be set with your actual values
echo "⚠️  Please set these manually with your actual credentials:"
echo "   railway variables set DISCORD_APPLICATION_ID=your_discord_app_id"
echo "   railway variables set DISCORD_CLIENT_SECRET=your_discord_secret"
echo "   railway variables set TELEGRAM_BOT_TOKEN=your_telegram_token"
echo "   railway variables set WHOP_API_KEY=your_whop_api_key"

# AI Services
echo "🤖 Setting AI service configuration..."
echo "⚠️  Please set these manually with your actual API keys:"
echo "   railway variables set GEMINI_API_KEY=your_gemini_api_key"
echo "   railway variables set OPENROUTER_API_KEY=your_openrouter_api_key"

# ===========================================
# SERVICE-SPECIFIC VARIABLES
# ===========================================

echo "🔧 Setting service-specific variables..."

# WEB SERVICE
echo "Setting web service variables..."
railway service omnipost
railway variables set SERVICE_NAME="omnipost-web"
railway variables set PORT="3000"
railway variables set NEXT_PUBLIC_APP_URL="https://omnipost-production.up.railway.app"

# Service URLs for inter-service communication
railway variables set WORKER_SERVICE_URL="http://omnipost-worker:3001"
railway variables set AI_SERVICE_URL="http://omnipost-ai:3002"

# WORKER SERVICE
echo "Setting worker service variables..."
railway service omnipost-worker
railway variables set SERVICE_NAME="omnipost-worker"
railway variables set WORKER_PORT="3001"
railway variables set WEB_SERVICE_URL="http://omnipost:3000"
railway variables set AI_SERVICE_URL="http://omnipost-ai:3002"

# AI SERVICE
echo "Setting AI service variables..."
railway service omnipost-ai
railway variables set SERVICE_NAME="omnipost-ai"
railway variables set AI_SERVICE_PORT="3002"
railway variables set WEB_SERVICE_URL="http://omnipost:3000"
railway variables set WORKER_SERVICE_URL="http://omnipost-worker:3001"

# ===========================================
# DATABASE URLS (Auto-generated by Railway)
# ===========================================

# Switch back to main service
railway service omnipost

echo "✅ Environment variables setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Set your actual API credentials manually:"
echo "   - Discord, Telegram, Whop API keys"
echo "   - Supabase URL and API keys" 
echo "   - AI provider API keys"
echo ""
echo "2. Deploy each service:"
echo "   railway service omnipost && railway up"
echo "   railway service omnipost-worker && railway up"
echo "   railway service omnipost-ai && railway up"
echo ""
echo "3. Check service health:"
echo "   railway logs --tail"
echo ""

# Display current services
echo "🏗️  Current services in project:"
railway list
