-- Missing user_notifications table for public schema
CREATE TABLE IF NOT EXISTS public.user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('post_published', 'post_failed', 'approval_needed', 'best_time', 'connection_error', 'quota_warning', 'welcome', 'setup_reminder')),
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_id ON public.user_notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_read ON public.user_notifications (user_id, read);
CREATE INDEX IF NOT EXISTS idx_user_notifications_created_at ON public.user_notifications (created_at);

-- Enable RLS (Row Level Security)
ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for authenticated users to access their own notifications
-- Using string comparison since auth.uid() returns UUID and user_id is BIGINT
CREATE POLICY "Users can access their own notifications" ON public.user_notifications
    FOR ALL USING (auth.uid()::text = user_id::text);
